<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.weili.example</groupId>
        <artifactId>weili-framework-example</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>weili-example-starter</artifactId>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>
    <dependencies>
        <!-- 内部依赖 -->
        <dependency>
            <groupId>com.weili.example</groupId>
            <artifactId>weili-example-dal</artifactId>
        </dependency>
        <dependency>
            <groupId>com.weili.example</groupId>
            <artifactId>weili-example-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.weili.example</groupId>
            <artifactId>weili-example-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.weili.example</groupId>
            <artifactId>weili-example-proxy</artifactId>
        </dependency>

        <dependency>
            <groupId>com.weili.basic</groupId>
            <artifactId>weili-basic-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.weili.basic</groupId>
            <artifactId>weili-basic-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>com.weili.basic</groupId>
            <artifactId>weili-basic-apollo</artifactId>
        </dependency>
        <dependency>
            <groupId>com.weili.basic</groupId>
            <artifactId>weili-basic-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.weili.basic</groupId>
            <artifactId>weili-basic-elasticsearch</artifactId>
        </dependency>
        <dependency>
            <groupId>com.weili.basic</groupId>
            <artifactId>weili-basic-xxljob</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.loki4j</groupId>
            <artifactId>loki-logback-appender</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-trace</artifactId>
        </dependency>
        <dependency>
            <groupId>net.logstash.logback</groupId>
            <artifactId>logstash-logback-encoder</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.skywalking</groupId>
            <artifactId>apm-toolkit-logback-1.x</artifactId>
        </dependency>
        <dependency>
            <groupId>org.codehaus.janino</groupId>
            <artifactId>janino</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>