<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.weili.example</groupId>
        <artifactId>weili-framework-example</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>weili-example-starter</artifactId>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>
    <dependencies>
        <!-- 内部依赖 -->
        <dependency>
            <groupId>com.weili.example</groupId>
            <artifactId>weili-example-dal</artifactId>
        </dependency>
        <dependency>
            <groupId>com.weili.example</groupId>
            <artifactId>weili-example-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.weili.example</groupId>
            <artifactId>weili-example-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.weili.example</groupId>
            <artifactId>weili-example-service</artifactId>
        </dependency>
        <dependency>
            <groupId>com.weili.example</groupId>
            <artifactId>weili-example-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>com.weili.example</groupId>
            <artifactId>weili-example-task</artifactId>
        </dependency>

        <dependency>
            <groupId>com.weili.basic</groupId>
            <artifactId>weili-basic-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.weili.basic</groupId>
            <artifactId>weili-basic-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>com.weili.basic</groupId>
            <artifactId>weili-basic-xxljob</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
        <dependency>
            <groupId>com.weili.basic</groupId>
            <artifactId>weili-basic-starter</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>weili-example-service</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.weili.example.starter.ExampleApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>