<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.weili.iot.portal</groupId>
        <artifactId>iot-business</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>iot-business-device-base</artifactId>
    <packaging>pom</packaging>

    <name>iot-business-device-base</name>
    <description>Device base data management module (master data) - 设备基础数据管理模块（主数据）</description>

    <modules>
        <module>device-base-api</module>
        <module>device-base-domain</module>
        <module>device-base-dal</module>
        <module>device-base-service</module>
        <module>device-base-web</module>
    </modules>
</project>

