server:
  port: 8081

spring:
  application:
    name: example-service
    # Jackson 配置项
  jackson:
    serialization:
      write-dates-as-timestamps: true # 设置 Date 的格式，使用时间戳
      write-date-timestamps-as-nanoseconds: false # 设置不使用 nanoseconds 的格式。例如说 1611460870.401，而是直接 1611460870401
      write-durations-as-timestamps: true # 设置 Duration 的格式，使用时间戳
      fail-on-empty-beans: false # 允许序列化无属性的 Bean
  main:
    allow-circular-references: true # 允许循环依赖
  # 禁用JMX
  jmx:
    enabled: false
  # 禁用RMI
  rmi:
    enabled: false
    # 禁用 RMI 远程连接（JMX 仍可用，但只能本地访问）
    registry:
      port: -1  # 禁用 RMI 注册端口
    server:
      port: -1    # 禁用 RMI 服务端口

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
apollo:
  bootstrap:
    enabled: true
  cache-dir: /opt/data/apollo-cache

logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log
  config: classpath:logback-spring.xml