server.port=9568
spring.application.name=weili-framework-example
# 数据库配置，只配置database
spring.datasource.master.database=wl_sdt
spring.datasource.slave.database=wl-mgs
# redis
spring.data.redis.database=12
# apollo
apollo.bootstrap.enabled=true
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info
logging.file.name=${user.home}/logs/${spring.application.name}.log
logging.config=classpath:logback-spring-test.xml
logging.level.org.springframework.boot.context.properties=DEBUG