apollo.bootstrap.enabled=true
apollo.bootstrap.eagerLoad.enabled=true
server.port=8080
spring.application.name=weili-iot-portal
# spring健康检查端口
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=beans,health,info,prometheus

#apollo配置namespace说明
# 1.默认包含application，无需单独配置
# 2.引入基础组件weili-boot-parent自带的公共namespace，无需单独配置
# 3.业务方自定义的namespace、需要再bean初始化加载之前的namespace此处需要配置
apollo.bootstrap.namespaces=weili.middleware.oauth2

#log配置，只在debug下打开，生产禁止打开
#logging
#  level:
#    com.weili.iot_portal.dal.mapper: TRACE
#    org.apache.ibatis: TRACE
#    com.baomidou.mybatisplus: DEBUG
#    java.sql: DEBUG
#    java.sql.ResultSet: DEBUG

# # 关闭Spring Bean初始化详细日志
# logging.level.org.springframework.beans.factory.support=WARN
# # 关闭XXL-JOB详细日志
# logging.level.com.xxl.job=WARN
# logging.level.com.wbasic.xxljob=WARN
# # 关闭Apollo配置中心详细日志
# logging.level.com.ctrip.framework.apollo=WARN
# # 关闭Spring Boot Actuator详细日志
# logging.level.org.springframework.boot.actuate=WARN
# # 关闭Redis/Lettuce详细日志
# logging.level.io.lettuce=WARN
# # Webhook Debug日志配置
# logging.level.com.weili.iot_portal.web.webhook=DEBUG
# logging.level.com.weili.iot_portal.service.ingestion=DEBUG
# logging.level.com.weili.iot_portal.service.ingestion.handler=INFO
# logging.level.com.weili.iot_portal.service.ingestion.support=INFO
