apollo.bootstrap.enabled=true
apollo.bootstrap.eagerLoad.enabled=true
server.port=8080
spring.application.name=weili-iot-portal

# spring健康检查端口
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=beans,health,info,prometheus

#apollo配置namespace说明
# 1.默认包含application，无需单独配置
# 2.引入基础组件weili-boot-parent自带的公共namespace，无需单独配置
# 3.业务方自定义的namespace此处需要配置
apollo.bootstrap.namespaces=

#log配置，只在debug下打开，生产禁止打开
#logging
#  level:
#    com.weili.iot_portal.dal.mapper: TRACE
#    org.apache.ibatis: TRACE
#    com.baomidou.mybatisplus: DEBUG
#    java.sql: DEBUG
#    java.sql.ResultSet: DEBUG