#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
server.port=9568
spring.application.name=${parentArtifactId}
${symbol_pound} 数据库配置，只配置database
spring.datasource.master.database=wl_sdt
spring.datasource.slave.database=wl-mgs
${symbol_pound} redis
spring.data.redis.database=12
${symbol_pound} apollo
apollo.bootstrap.enabled=true
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info
logging.file.name=${symbol_dollar}{user.home}/logs/${symbol_dollar}{spring.application.name}.log
logging.config=classpath:logback-spring-test.xml
logging.level.org.springframework.boot.context.properties=DEBUG