<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.weili.iot.portal</groupId>
        <artifactId>iot-business</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>iot-business-common</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>common-api</module>
        <module>common-domain</module>
    </modules>

    <description>Business Common Module - 业务公共模块（包含班次管理等公共功能）</description>
</project>

